# Fabric Properties
	# check these on https://fallen-breath.github.io/fabric-versions/?version=26.1&mappings=yarn
	minecraft_version=26.1

# Fabric Mod Metadata
	minecraft_dependency=26.1.x
	fabric_dependency=fabric-api

# Build Information
	# The target mc versions for the mod during mod publishing, separated with \n
	game_versions=26.1\n26.1.1\n26.1.2

# Dependencies
	fabric_api_version=0.148.0+26.1.2
